Добавлен базовый функционал расширения
irsural/sphinx-flyout pull request #1
Opened 2024-02-29 06:56 UTC by UnicPlay

2024-03-01 05:21 UTC, Feelinglight requested changes

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
Версии чего

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Заголовок меню. По умолчанию - "Flyout"
По умолчанию брать стандартный ``project`` из conf.py

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Заголовок меню. По умолчанию - "Flyout"
И проверить как он будет отображаться на длинных именах

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +По умолчанию - `http://0.0.0.0:8000`
Дефолт не нужен. Обязательный аргумент

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Словарь структуры `{текст1: ссылка1, текст2: ссылка2, ...}`
Не надо. Нужна просто ссылка на git репозиторий.
Обязательный аргумент

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Словарь структуры `{текст1: ссылка1, текст2: ссылка2, ...}`
Давай пока что не словарь, а список форматов.
Пример: ['HTML', 'PDF']
Текст генерируется по имени формата.
Итоговая ссылка ``sphinx_flyout_host/{project}/download/{format}``

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +#### ``sphinx_flyout_versions``
Отдельно список ветое и тэгов.

Пример:

sphinx_flyout_branches = ['master', 'develop']
Итоговая ссылка ``sphinx_flyout_host/{project}/branch/master`` и т. д.

С тэгами аналогично

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
Это должно браться из тэга либо из ветки.
Если это сайт по ветке master, то там должно быть master

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +#### ``sphinx_flyout_gitea``
sphinx_flyout_repository_link

2024-03-01 05:21 UTC, Feelinglight commented on README.md
> +![flyout](docs/images/menu.png)
Заголовки ссылок во flyout, типа Versions, Downloads должны быть русскими: Ветки, Тэги, Загрузки и т. д.

2024-03-01 05:21 UTC, Feelinglight commented on pyproject.toml
> +[tool.ruff.lint]
Где настройки mypy?

2024-03-01 06:22 UTC, UnicPlay commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
Проект Sphinx не обязательно git-репозиторий. В автоматической сборке в раннере можно будет задать этот параметр через командную строку

2024-03-01 06:28 UTC, UnicPlay commented on README.md
> +По умолчанию - `http://0.0.0.0:8000`
В Sphinx нельзя в расширении задать обязательный аргумент. 

Как вариант, можно сделать в начале работы расширения проверку на наличие аргумента, и вызывать `ConfigError` (= ронять сборку), либо писать в логи ошибку и отрубать работу расширения

2024-03-01 06:29 UTC, UnicPlay commented on README.md
> +Словарь структуры `{текст1: ссылка1, текст2: ссылка2, ...}`
\+

2024-03-01 06:29 UTC, UnicPlay commented on README.md
> +Словарь структуры `{текст1: ссылка1, текст2: ссылка2, ...}`
\+

2024-03-01 06:29 UTC, UnicPlay commented on README.md
> +#### ``sphinx_flyout_versions``
\+

2024-03-01 06:29 UTC, UnicPlay commented on README.md
> +#### ``sphinx_flyout_gitea``
\+

2024-03-01 06:29 UTC, UnicPlay commented on README.md
> +![flyout](docs/images/menu.png)
\+

2024-03-01 06:30 UTC, UnicPlay commented on pyproject.toml
> +[tool.ruff.lint]
Забыл, они у меня лежат просто на диске
Добавил

2024-03-01 07:56 UTC, UnicPlay commented on README.md
> +Заголовок меню. По умолчанию - "Flyout"
Слишком длинное имя ломается, увозит иконку вбок
![изображение](https://github.com/irsural/sphinx-flyout/assets/43138284/b3edc834-92b7-410c-9197-f078c61c758d)

2024-03-01 08:03 UTC, UnicPlay commented on README.md
> +Заголовок меню. По умолчанию - "Flyout"
> По умолчанию брать стандартный `project` из conf.py

\+

2024-03-01 11:43 UTC, Feelinglight commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
У нас обязательно

2024-03-01 11:47 UTC, Feelinglight commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
Хотя это не отменяет того что экшен должен будет отправлять на сервер ветку или тэг, по которым собран сайт

2024-03-01 11:48 UTC, Feelinglight commented on README.md
> +Заголовок меню. По умолчанию - "Flyout"
Сойдёт. К тому же css скриптами наверняка можно поправить

2024-03-01 11:49 UTC, Feelinglight commented on README.md
> +По умолчанию - `http://0.0.0.0:8000`
Бросать ConfigError с описанием ошибки

2024-03-01 12:31 UTC, UnicPlay commented on README.md
> +По умолчанию - `http://0.0.0.0:8000`
\+

2024-03-01 12:56 UTC, Feelinglight requested changes

2024-03-01 12:56 UTC, Feelinglight commented on mypy.ini
> +exclude = ("^venv\.")
Это лишнее, просто добавь в gitignore. Как и все файлы которые не коммитятся

2024-03-01 12:56 UTC, Feelinglight commented on templates/versions.html
> +        <dt>Тэги</dt>
Сначала ветки потом тэги

2024-03-01 13:49 UTC, UnicPlay commented on README.md
> +Строковое значение версии в меню. По умолчанию - `1.0`
\+

2024-03-01 13:55 UTC, UnicPlay commented on templates/versions.html
> +        <dt>Тэги</dt>
\+

2024-03-01 13:55 UTC, UnicPlay commented on mypy.ini
> +exclude = ("^venv\.")
\+

2024-03-04 04:26 UTC, Feelinglight commented on mypy.ini
> +exclude = ("^venv\.")
Указать в files путь до __main__

2024-03-05 12:42 UTC, UnicPlay commented on mypy.ini
> +exclude = ("^venv\.")
\+

2024-03-11 06:41 UTC, Feelinglight commented on mypy.ini
> +exclude = ("^venv\.")
https://okr.irsural.ru/master/ИРС/Правила%20разработки/Python/300.%20Mypy.html#id3

2024-03-11 06:49 UTC, Feelinglight commented on README.md
> +#### ``sphinx_flyout_versions``
Вот это сделано неверно. Не вижу {project}. В текущем варианте разные сайты подерутся за ссылки

2024-03-12 02:43 UTC, Feelinglight requested changes

2024-03-12 02:43 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +    app.connect('builder-inited', _check_config_values)
Логично в первую очередь проверить конфигурацию, а потом уже все остальное

2024-03-12 02:43 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +    config.templates_path.append(str(Path(__file__).parent.parent / "templates"))
Папку templates перенести sphinx_flyout и назвать _templates

2024-03-12 02:43 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +    process = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
git branch --show-current
Понятнее, вывод такой же

2024-03-12 02:43 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +        return ""
Возвращать unknown вместо пустой строки

2024-03-12 02:43 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +        new_links[link] = f"{host}/{section}/{link}"
Думаю стоит сделать lower()

2024-03-12 07:43 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +        new_links[link] = f"{host}/{section}/{link}"
\+

2024-03-12 08:02 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +    process = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
Может быть git branch --show-current || git describe --tags --exact-match --abbrev=0 ?
Если есть имя ветки - даст ветку, если нет - даст имя тэга, если нет ничего - в stdout не даст ничего

2024-03-12 08:24 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +    app.connect('builder-inited', _check_config_values)
\+

2024-03-12 11:24 UTC, UnicPlay commented on README.md
> +#### ``sphinx_flyout_versions``
\+

2024-03-12 11:28 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +    app.connect('builder-inited', _check_config_values)
\+

2024-03-12 11:30 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +    config.templates_path.append(str(Path(__file__).parent.parent / "templates"))
\+

2024-03-12 11:33 UTC, UnicPlay commented on sphinx_flyout/__init__.py
> +        return ""
\+

2024-03-12 12:12 UTC, UnicPlay commented on mypy.ini
> +exclude = ("^venv\.")
Но ведь у меня нет иных точек входа, кроме `sphinx_flyout/__init__.py` ? Или я что-то недопонимаю?

2024-03-13 05:48 UTC, Feelinglight commented on README.md
> +#### ``sphinx_flyout_versions``
А документацию кто менять будет

2024-03-13 05:49 UTC, Feelinglight commented on mypy.ini
> +exclude = ("^venv\.")
Именно. А что у тебя в mypy.ini указано?

2024-03-13 09:18 UTC, Feelinglight commented on sphinx_flyout/__init__.py
> +    process = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
Обсудили лично

2024-03-22 08:09 UTC, Feelinglight requested changes
Документация

2024-03-22 08:25 UTC, Feelinglight reviewed
Не работает с такими параметрами

```python
sphinx_flyout_header = "Menu header"
sphinx_flyout_repository_link = "https://github.com/irsural/sphinx-flyout"
sphinx_flyout_host = "localhost"
sphinx_flyout_downloads = ['html', 'source']

sphinx_flyout_branches = [
    'master', 'zorin', 'Pryaminin', 'ivashenko', 'nalimov', 'poliekhov', 'krasheninnikov', 'ququ'
]
sphinx_flyout_tags = ['kkk', '555', '444', 'qaqa']
```

2024-03-27 03:12 UTC, merged