Удалён flyout_multiversion
irsural/sphinx-flyout pull request #11
Opened 2024-09-04 13:05 UTC by UnicPlay

2024-09-05 05:18 UTC, Feelinglight requested changes

2024-09-05 05:18 UTC, Feelinglight commented on .github/workflows/ruff_mypy_check.yaml
> +          cache: "pip"
Почему 3.10?

2024-09-05 05:18 UTC, Feelinglight commented on Makefile
> -	python3 -m ruff format sphinx_flyout/*.py flyout_multiversion/*.py tests/*.py --check
Почему убраны тесты?

2024-09-06 04:20 UTC, UnicPlay commented on Makefile
> -	python3 -m ruff format sphinx_flyout/*.py flyout_multiversion/*.py tests/*.py --check
потому что все тесты написаны для flyout_multiversion

2024-09-06 05:52 UTC, Feelinglight approved these changes

2024-09-06 05:52 UTC, merged