Добавлен скрипт для сборки нескольких версий документации
irsural/sphinx-flyout pull request #2
Opened 2024-04-10 11:42 UTC by UnicPlay

2024-04-12 11:12 UTC, Feelinglight requested changes
Попытаться разбить на несколько пулл реквестов

2024-04-12 15:45 UTC, UnicPlay commented
Как можно разбить: первым пул реквестом добавить полный функционал sphinx_multiversion, без правок (и без необходимости ревью). Вторым - правки в этот код. Третьим - удаление старого расширения(опционально), правки в README, pyproject. Прочие способы разбиения, скорее всего, поломают возможность взаимодействия с новым расширением.

2024-04-15 06:35 UTC, Feelinglight commented
> Как можно разбить: первым пул реквестом добавить полный функционал sphinx_multiversion, без правок (и без необходимости ревью). Вторым - правки в этот код. Третьим - удаление старого расширения(опционально), правки в README, pyproject. Прочие способы разбиения, скорее всего, поломают возможность взаимодействия с новым расширением.

Нет, это бесполезно

2024-04-15 06:36 UTC, Feelinglight commented
Разбить по другому можно. Как минимум можно, например сделать пулл реквест на модуль git. Он ни от чего не зависит

2024-04-15 06:36 UTC, Feelinglight commented
Можно аргументы cli отдельно закоммитить

2024-04-15 06:36 UTC, Feelinglight commented
И т. д.

2024-04-15 06:36 UTC, Feelinglight commented
Все функции должны быть задокументированы и покрыты тестами

2024-04-15 06:37 UTC, Feelinglight commented
2х main-ов быть не должно

2024-04-16 06:04 UTC, closed without merging