Добавлены вспомогательные функции для системы управления версиями Git
irsural/sphinx-flyout pull request #3
Opened 2024-04-15 10:29 UTC by UnicPlay

- `get_toplevel_path`, для поиска пути верхнего уровня к репозиторию Git
- `get_all_refs`, для получения всех ссылки на Git (ветви, теги, удаленные ссылки).
- `get_refs` для фильтрации ссылок на основе белых списков и требуемых файлов
- `file_exists`, для проверки существования файла по заданной ссылке
- `copy_tree`, для копирования дерева git-репозитория в требуемую папку

2024-04-15 11:34 UTC, Feelinglight requested changes
Забыл что ли как функции документировать? Пиши докстринги. 

Не вижу тестов

2024-04-18 05:27 UTC, Feelinglight requested changes

2024-04-18 05:27 UTC, Feelinglight commented on flyout_multiversion/git.py
> +class GitError(Exception):
В отдельный файл errors.py. Отнаследуй кстати его сразу от ExtensionError. Не придется бесполезными перехватами заниматься

2024-04-18 05:27 UTC, Feelinglight commented on flyout_multiversion/git.py
> +VersionRef = namedtuple(
Объяви через наследование от NamedTuple

2024-04-18 05:27 UTC, Feelinglight commented on tests/test_flyout_multiversion_git.py
> +def repo(tmp_path: Path) -> Path:
tmp_repo_path

2024-04-18 05:27 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    :param cwd: Путь к текущей рабочей директории (по умолчанию None)
Не надо писать текстом умолчания, они из сигнатуры видны

2024-04-18 05:27 UTC, Feelinglight commented on flyout_multiversion/git.py
> +def get_all_refs(gitroot: str) -> Iterator[VersionRef]:
Это где-то используется? Удали все функции, которые не используются. После этого буду проверять дальше.

2024-04-18 05:38 UTC, UnicPlay commented on flyout_multiversion/git.py
> +def get_all_refs(gitroot: str) -> Iterator[VersionRef]:
???
Да хотя бы [в этом же файле](https://github.com/irsural/sphinx-flyout/blob/b8511388695bf2aebbfcb84ebb1f1cbf059c159b/flyout_multiversion/git.py#L114)

2024-04-18 08:25 UTC, Feelinglight commented on flyout_multiversion/git.py
> +def get_all_refs(gitroot: str) -> Iterator[VersionRef]:
Посмотрел только в файле, где его импортируют, сорри. Сделай все функции которые не нужны снаружи приватными, с одним подчеркиванием

2024-04-19 10:05 UTC, Feelinglight requested changes

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    :return: Ссылки Git-репозитория в формате VersionRef
Типы тоже писать не надо, они видны из сигнатуры. Исправить везде

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    :param files: Кортеж обязательных файлов
Обязательных для чего?

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    Итерируется по отфильтрованным ссылкам (refs) в Git-репозитории.
Нужно более внятное описание. Не особо очевидно ни что такое отфильтрованные ссылки, ни что такое "разрешенные" тэги/ветки и т. д.

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +def _file_exists(gitroot: str, refname: str, filename: str) -> bool:
Все пути к файлам поменять на Path

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +        filename = filename.replace(os.sep, "/")
Здесь видимо будет path.as_posix() без if-а

2024-04-19 10:05 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    Копирует содержимое указанной ссылки (ref) из Git-репозитория в целевую директорию.
У тебя везде неверно используется слово ссылка.
Файлы не могут быть "в ссылке", и у ссылки нет содержимого. Файл или содержимое есть у **коммита** по ссылке

2024-04-19 10:05 UTC, Feelinglight commented on tests/test_flyout_multiversion_git.py
> +    subprocess.check_call(["git", "commit", "--allow-empty", "-m", "Initial commit"])
Сделай удобные функции для вызова подобных команд. Что это за мазахизм. create_branch, create_tag и т. д.

2024-05-02 10:39 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    :param files: Кортеж обязательных файлов
Не сделано

2024-05-02 10:49 UTC, Feelinglight requested changes

2024-05-02 10:49 UTC, Feelinglight commented on flyout_multiversion/git.py
> +    files: tuple[str | Path, ...] = (),
Зачем здесь str?

2024-05-21 09:50 UTC, Feelinglight requested changes
Не все замечания исправлены

2024-05-22 04:27 UTC, Feelinglight approved these changes

2024-05-22 04:27 UTC, merged