Добавлено расширение для создания flyout_menu (для сборки нескольких версий)
irsural/sphinx-flyout pull request #8
Opened 2024-06-21 07:31 UTC by UnicPlay

2024-06-21 07:44 UTC, Feelinglight requested changes

2024-06-21 07:44 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +Version = collections.namedtuple(
Сделай наследование от NamedTuple

2024-06-21 07:44 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +DATE_FMT = '%Y-%m-%d %H:%M:%S %z'
Аннотируй типом Final все константы

2024-06-21 07:44 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +def setup(app: Sphinx) -> None:
Перенеси эту функцию в самый верх файла

2024-06-21 07:44 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_flyout_tag_list', DEFAULT_REF_WHITELIST, 'html')
Зачем вся эта пачка параметров? Мы договаривались только на объединение sphinx_flyout_branches и sphinx_flyout_tags в один словарь. Остальные изменения зачем?

2024-06-21 11:34 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_flyout_tag_list', DEFAULT_REF_WHITELIST, 'html')
Не сделано

2024-06-21 11:35 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +class Version(NamedTuple):
Все типы и константы должны быть перед функциями

2024-06-21 11:35 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +DATE_FMT = '%Y-%m-%d %H:%M:%S %z'
Не сделано

2024-06-21 11:36 UTC, Feelinglight requested changes
Исправить

2024-06-21 11:42 UTC, UnicPlay commented on flyout_multiversion/_sphinx.py
> +DATE_FMT: Final = '%Y-%m-%d %H:%M:%S %z'
Сделано же...

2024-06-21 13:55 UTC, Feelinglight requested changes

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Что за версия? Где хэдер?

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    necessary_values = [
Это называется required

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +"""
Почему файл называется с нижнего подчеркивания

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    config.templates_path.insert(0, str(Path(__file__).parent / '_templates'))
Почему в multiversion таких костылей нет?

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +            name: host + '/branches/' + name for name in app.config.fmv_flyout_branch_list
Что если 10 проектов с мастером будет?

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +            name: host + '/branches/' + name for name in app.config.fmv_flyout_tag_list
Аналогично

2024-06-21 13:55 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +            name: host + '/download/' + name for name in app.config['fmv_flyout_downloads']
Аналогично

2024-06-26 05:57 UTC, UnicPlay commented on flyout_multiversion/_sphinx.py
> +    config.templates_path.insert(0, str(Path(__file__).parent / '_templates'))
Иначе нельзя указать файл шаблона
В исходном коде шаблон стандартный для sphinx_rtd_theme, у нас же шаблон свой (переведённый на русский и с разделением веток и тэгов)

2024-06-26 06:12 UTC, UnicPlay commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Версия - зелёный текст в правой части flyout
Хэдер определяется [ниже](https://github.com/irsural/sphinx-flyout/blob/4398fb290f25790b792c61eba660ddf30274bb1e/flyout_multiversion/_sphinx.py#L202), чтоб была возможность добавить ему значение по умолчанию в виде названия проекта в sphinx 
![image](https://github.com/irsural/sphinx-flyout/assets/43138284/0ec64fa1-15f0-44d6-a30e-0e5a116ac2bd)

2024-06-26 09:46 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Зеленый текст должен определяться веткой или тэгом. Список параметров **утвержден уже 100 лет назад** и описан в readme, сколько можно повторять.

У ``add_config_value`` есть параметр дефолт. Почему он не используется?

2024-06-26 09:58 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +            name: host + '/branches/' + name for name in app.config.fmv_flyout_branch_list
Проблема не решена

2024-06-26 09:59 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +            name: host + '/branches/' + name for name in app.config.fmv_flyout_branch_list
Даже если бы версия не была веткой или тэгом, то 10 проектов могли бы иметь одинаковую версию

2024-06-26 10:03 UTC, Feelinglight requested changes
Исправить оставшиеся замечания

2024-06-26 11:12 UTC, UnicPlay commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Используется. В Sphinx есть несколько значений по умолчанию, одно из них - project=Python.
Если указать add_config_value("fmv_flyout_header", default=app.config.project) в функции setup, то в ситуации, когда имя проекта указано, а имя хэдера не указано - имя хэдера будет Python. На 1 схемке именно это и нарисовано. 
![image](https://github.com/irsural/sphinx-flyout/assets/43138284/d06aa26a-a1f6-402b-a60b-30686193412b)
Чтоб это обойти - нужно добавить config_value после инициализации конфигурации, т.е. так, как на 2 схеме
![image](https://github.com/irsural/sphinx-flyout/assets/43138284/3384c3ce-1d23-4470-b30a-3022e7562cde)

2024-06-26 13:16 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +        )
А тэги где. Это должно определяться не коммитом на котором ты находишься, а веткой/тэгом для которого в данный момент запущена сборка.

Мы же договаривались, что ты будешь multiversion переносить, а то что уже было сделано во flyout. То что было сделано я уже видел

2024-06-26 13:16 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Добавь комментарий к установке fmv_flyout_header, что app.config.project инициализируется после setup

2024-06-26 13:17 UTC, Feelinglight requested changes
Исправить замечания

2024-06-28 04:29 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +        )
Для того чтобы перенести сборку нескольких версий, необходимо перенести скрипт, собирающий несколько версий, а это нужно сделать в другом пул реквесте. Я пока переношу только надстройку для sphinx с генерацией flyout, а в пул реквесте с основным скриптом буду её модифицировать для работы со сборкой нескольких версий.

2024-06-28 04:57 UTC, Feelinglight commented on flyout_multiversion/_sphinx.py
> +    app.add_config_value('fmv_current_version', '', 'html')
Где?

2024-06-28 05:00 UTC, Feelinglight requested changes

2024-06-28 05:00 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +        project_url = host + '/' + quote(app.config['fmv_flyout_header'])
Если захочу сделать хэдер по другому то все ссылки полетят???

Составляй project_url из app.config.project

2024-06-28 08:05 UTC, Feelinglight approved these changes

2024-06-28 08:05 UTC, merged