Add multiversion script
irsural/sphinx-flyout pull request #9
Opened 2024-07-07 11:15 UTC by UnicPlay

2024-07-08 13:17 UTC, Feelinglight requested changes

2024-07-08 13:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +    app.add_config_value('fmv_metadata_path', '', 'html')
Что это такое опять?

2024-07-08 14:24 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +    app.add_config_value('fmv_metadata_path', '', 'html')
Это самый простой способ передавать данные между сборками, эти параметры всё равно скриптом во время выполнения переопределяются, их не нужно заполнять вообще, это чисто внутренняя кухня. Могу для видимости добавить им нижнее подчёркивание в начало названия.

2024-07-10 11:17 UTC, Feelinglight requested changes
Нет описания пул реквеста

2024-07-11 15:12 UTC, UnicPlay commented
Скрипт собирает несколько версий (веток и тэгов репозитория) документации с помощью Sphinx. Данные о собираемых версиях получаются из конфигурационного файла Sphinx текущей версии. В процессе сборки формируется flyout-меню с помощью расширения flyout_multiversion.flyout_menu. Данные для создания меню передаются в сборку отдельной версии посредством файла с метаданными, расположенного в `/tmp/multiversion_metadata.json`.
После создания файла с метаданными для каждой собираемой версии вызывается сборка Sphinx с дополнением конфигурации этой версии общими данными из изначального конфигурационного файла: ссылки на прочие собираемые версии, указанные при запуске скрипта переопределения config overrides

2024-07-12 08:17 UTC, Feelinglight requested changes

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/__main__.py
> +METADATA_PATH: Final = '/tmp/multiversion_metadata.json'
Сохраняй в папку с билдом

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +from flyout_multiversion.__main__ import METADATA_PATH
Из точек входа не должно ничего импортироваться

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +    app.add_config_value('fmv_tag_build_list', [], 'html')
В таком подходе изменения в этом файле будут постоянно висеть в гите и их нужно будет откатывать перед коммитом, либо не включать в коммит. Кто нибудь обязательно ошибется и закоммитит это.

Думаю нужно сделать булев флаг "собирать только текущий коммит", который можно будет указывать через консоль, если нужно.

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +import json
Этот файл либо должен называться так же как пакет, либо его содержимое должно быть в \_\_init__

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +def config_inited(app: Sphinx, config: Config) -> None:
Это когда и кем вызывается?

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +    app.connect('html-page-context', html_page_context)
Зачем делать это второй раз?

2024-07-12 08:17 UTC, Feelinglight commented on flyout_multiversion/flyout_menu.py
> +    old_config.init_values()
Что тут происходит?

2024-07-12 11:07 UTC, Feelinglight reviewed
Напиши **как** это работает

2024-07-13 13:27 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +def config_inited(app: Sphinx, config: Config) -> None:
Это вызывается Sphinx'ом во время сборки одной из версий

2024-07-13 13:33 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +def config_inited(app: Sphinx, config: Config) -> None:
Только сейчас заметил, что не вызывал это в setup. Исправил.

2024-07-13 13:37 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +    old_config.init_values()
Инициализируются данные из конфига версии, из которой вызвана сборка

2024-07-13 14:03 UTC, UnicPlay commented on flyout_multiversion/flyout_menu.py
> +    app.add_config_value('fmv_tag_build_list', [], 'html')
Не понял про изменения в файле.
Если нужно посмотреть как выглядит один коммит - запускается sphinx-build
Если нужно собрать сразу все версии из build_list'ов - запускается flyout_multiversion

2024-07-13 14:37 UTC, UnicPlay commented
Для работы нужно добавить flyout_multiversion в список расширений и установить необходимые переменные в conf.py (`fmv_flyout_host`, `fmv_branch_build_list` или `fmv_tag_build_list`). 
Для простоты объяснения пусть репозиторий находится в `/home/user/repo`, а готовый сайт будет в `/home/user/build`
При запуске flyout_multiversion происходит следующее: 
В временные папки средствами git копируются все указанные в `fmv_branch_build_list` и `fmv_tag_build_list` версии репозитория (последние коммиты). 
Затем для каждой из этих папок: 
  - инициализируется конфигурационный файл **текущей** версии (`/home/user/repo`),
  - обновляется данными конфигурационного файла **собираемой** версии (`/tmp/98q64yfihis/some_commit_hash`), 
  - версия собирается средствами Sphinx,
  - собранная версия помещается в `/home/user/build/branches/branch_name` или `/home/user/build/tags/tag_name`

2024-09-02 13:00 UTC, closed without merging